services:
  gg\WhiteListApiBundle\Factory\WhiteListFactory:
    public: true
    arguments:
      - ~

  gg\WhiteListApiBundle\Factory\WhiteListFactoryInterface: '@gg\WhiteListApiBundle\Factory\WhiteListFactory'
